### ISSUE TITLE
Retorno de datos en NONE en busquedas varias

### ISSUE THREAD

**Issue by sebastian-bascu** [Atixx/ARMMA#7]
Corroborar la validez de los datos en varias consultas que estan retornando None, puede indicar error de calculo

Ejemplo: todas las edades, en 1993, sexo indistinto, causa indisinto.

**Comment by Atixx** [comment]
Hay que diferenciar entre un 0, con un No hay datos (en la busqueda de datos)

**Comment by Atixx** [comment]
Encontre un error en el calculo de datos, reflejado y arreglado en el commit 2bd854d 
Posible fix para este tema
